#Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1, joint2, joint3, joint4]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
  
#Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints
standford_arm_group_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5]
  
standford_hand_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_6a, joint_6b]

  #Instead of using TAB for indentation, use two spaces at the place of one TAB
#Controller to control robot arm joints
achs_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1_6achs, joint_2_6achs, joint_3_6achs, joint_4_6achs, joint_5_6achs, joint_6_6achs]


