robot_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - j1
    - j2
    - j3
    - j4
    - j5
    - j6
  gains:
    j1:
      p: 10
      d: 1
      i: 1
      i_clamp: 1
    j2:
      p: 10
      d: 1
      i: 1
      i_clamp: 1
    j3:
      p: 10
      d: 1
      i: 1
      i_clamp: 1
    j4:
      p: 10
      d: 1
      i: 1
      i_clamp: 1
    j5:
      p: 10
      d: 1
      i: 1
      i_clamp: 1
    j6:
      p: 10
      d: 1
      i: 1
      i_clamp: 1    
  constraints:
    goal_time: 0.1
    stopped_velocity_tolerance: 0.1
    joint1:
      goal: 0.1
      trajectory: 0.05
    joint2:
      goal: 0.1
      trajectory: 0.05
    joint3:
      goal: 0.1
      trajectory: 0.05
    joint4:
      goal: 0.1
      trajectory: 0.05
    joint5:
      goal: 0.1
      trajectory: 0.05
    joint6:
      goal: 0.1
      trajectory: 0.05
